name: Cron Job
on:
  schedule:
    - cron:  "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildx-version: latest
          skip-cache: false
          qemu-version: latest
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
          qemu-version: latest
      
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Runs a set of commands using the runners shell
      - name: Run Buildx
        run: |
          make all
          make publish
